--
-- File generated with SQLiteStudio v3.1.1 on Fri Jul 7 20:19:48 2017
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: MapSpawnStatistics
DROP TABLE IF EXISTS MapSpawnStatistics;

CREATE TABLE MapSpawnStatistics (
    StatisticId          INTEGER PRIMARY KEY AUTOINCREMENT,
    LocationId           INTEGER REFERENCES MapLocations (LocationId),
    SpawnSideId          INTEGER,
    SpawnSideDescription VARCHAR,
    RunDescription       VARCHAR,
    RunDuration          REAL
);

INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (1, 1, 1, 'Attack', 'Main to Forward Choke', 13.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (2, 1, 2, 'Defend', 'Left Side Bridge to Point to Forward Choke', 30);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (3, 1, 2, 'Defend', 'Left Side Bridge to Main to Forward Choke', 26.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (4, 1, 2, 'Defend', 'Main to Forward Choke', 27.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (5, 2, 1, 'Attack', 'Main to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (6, 2, 2, 'Defend', 'Left Side Bridge to Point', 23.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (7, 2, 2, 'Defend', 'Main to Point', 24.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (8, 3, 1, 'Attack', 'Main to Forward Choke', 18.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (9, 3, 2, 'Defend', 'Main to Forward Choke', 14.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (10, 4, 1, 'Attack', 'Main to Point', 22.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (11, 4, 1, 'Attack', 'Left through Crypts to Point', 27.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (12, 4, 1, 'Attack', 'Right over Wall to Point', 25.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (13, 4, 2, 'Defend', 'Left Spawn to Point', 8.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (14, 4, 2, 'Defend', 'Right Spawn to Point', 9.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (15, 5, 1, 'Attack', 'Main Right to Forward Choke', 17.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (16, 5, 2, 'Defend', 'Main to Forward Choke', 30.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (17, 6, 1, 'Attack', 'Main Right to Point', 24);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (18, 6, 1, 'Attack', 'Main Left to Point', 23.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (19, 6, 2, 'Defend', 'Main to Point', 26.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (20, 6, 2, 'Defend', 'Lower Left to Point', 24.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (21, 7, 1, 'Attack', 'Right Spawn to High Ground', 13.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (22, 7, 2, 'Defend', 'Far Left Spawn to Stairs to High Ground', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (23, 7, 2, 'Defend', 'Main Lower Left to Stairs to High Ground', 17.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (24, 8, 1, 'Attack', 'Main to Point', 19.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (25, 8, 1, 'Attack', 'Lower Right to Point', 18.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (26, 8, 1, 'Attack', 'Right High Ground to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (27, 8, 2, 'Defend', 'Right Spawn to Point', 9.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (28, 8, 2, 'Defend', 'Left Spawn to Point', 9.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (29, 8, 2, 'Defend', 'Far Left Spawn to Point', 10.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (30, 9, 1, 'Attack', 'Main Left to Forward Choke', 16.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (31, 9, 1, 'Attack', 'Main Right to Forward Choke', 16.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (32, 9, 2, 'Defend', 'Main to Forward Choke', 27.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (33, 10, 1, 'Attack', 'Main Left to Point', 20.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (34, 10, 1, 'Attack', 'Main Right to Point', 20.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (35, 10, 2, 'Defend', 'Main to Point', 27.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (36, 10, 2, 'Defend', 'Cliff Side Gap to Point', 25.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (37, 11, 1, 'Attack', 'Main to Forward Choke', 19.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (38, 11, 2, 'Defend', 'Left Spawn to Forward Choke', 13);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (39, 12, 1, 'Attack', 'Right Stairs to High Ground', 25.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (40, 12, 1, 'Attack', 'Right Bridge to High Ground', 24.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (41, 12, 2, 'Defend', 'Left Spawn to High Ground', 12.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (42, 13, 1, 'Attack', 'Main to Point', 21.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (43, 13, 2, 'Defend', 'Left Spawn to Point', 8.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (44, 13, 2, 'Defend', 'Right Spawn to Point', 9.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (45, 14, 1, 'Attack', 'Main through Building to Forward Choke', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (46, 14, 1, 'Attack', 'Ice Side Spawn to Forward Choke', 16.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (47, 14, 2, 'Defend', 'Main to Forward Choke', 26.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (48, 15, 1, 'Attack', 'Main through Building to Point', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (49, 15, 2, 'Defend', 'Main to Point', 25.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (50, 16, 1, 'Attack', 'Main to Forward Choke', 20);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (51, 16, 2, 'Defend', 'Left Spawn to Forward Choke', 14.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (52, 16, 2, 'Defend', 'Right Spawn to Forward Choke', 14.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (53, 17, 1, 'Attack', 'Main to Point', 23.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (54, 17, 1, 'Attack', 'Right Side to Point', 25.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (55, 17, 1, 'Attack', 'Lower Left Side to Point', 29.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (56, 17, 1, 'Attack', 'Upper Left Side to High Ground to Behind Point', 35.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (57, 17, 2, 'Defend', 'Left Spawn to Main to Point', 10.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (58, 17, 2, 'Defend', 'Left Spawn to Left to Point', 10.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (59, 17, 2, 'Defend', 'Right Spawn to Main to Point', 9.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (60, 18, 1, 'Attack', 'Main to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (61, 18, 1, 'Attack', 'Tunnel to Point', 20.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (62, 18, 1, 'Attack', 'Room Mega to Point', 20.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (63, 18, 2, 'Defend', 'Main to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (64, 18, 2, 'Defend', 'Tunnel to Point', 20.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (65, 18, 2, 'Defend', 'Room Mega to Point', 20.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (66, 19, 1, 'Attack', 'High Ground to Point', 20.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (67, 19, 1, 'Attack', 'Main Tunnel to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (68, 19, 1, 'Attack', 'Pool Mega to Point', 20.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (69, 19, 2, 'Defend', 'High Ground to Point', 20.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (70, 19, 2, 'Defend', 'Main Tunnel to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (71, 19, 2, 'Defend', 'Pool Mega to Point', 20.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (72, 20, 1, 'Attack', 'Main to Point', 16.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (73, 20, 1, 'Attack', 'Full City Side to Point', 20.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (74, 20, 1, 'Attack', 'Coast Side to Point', 19.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (75, 20, 2, 'Defend', 'Main to Point', 16.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (76, 20, 2, 'Defend', 'Full City Side to Point', 20.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (77, 20, 2, 'Defend', 'Coast Side to Point', 19.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (78, 21, 1, 'Attack', 'Main to Point', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (79, 21, 1, 'Attack', 'High Ground to Point', 21.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (80, 21, 1, 'Attack', 'Full Cliff Side to Point', 20.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (81, 21, 2, 'Defend', 'Main to Point', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (82, 21, 2, 'Defend', 'High Ground to Point', 21.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (83, 21, 2, 'Defend', 'Full Cliff Side to Point', 20.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (84, 22, 1, 'Attack', 'Main to Point', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (85, 22, 1, 'Attack', 'Dropdown to Point', 22.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (86, 22, 2, 'Defend', 'Main to Point', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (87, 22, 2, 'Defend', 'Dropdown to Point', 22.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (88, 23, 1, 'Attack', 'Under Bridge to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (89, 23, 1, 'Attack', 'Main to Point', 19.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (90, 23, 1, 'Attack', 'Over Bridge to Point', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (91, 23, 2, 'Defend', 'Under Bridge to Point', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (92, 23, 2, 'Defend', 'Main to Point', 19.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (93, 23, 2, 'Defend', 'Over Bridge to Point', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (94, 24, 1, 'Attack', 'Main to Point', 17.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (95, 24, 1, 'Attack', 'Outside to Point', 17.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (96, 24, 2, 'Defend', 'Main to Point', 17.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (97, 24, 2, 'Defend', 'Outside to Point', 17.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (98, 25, 1, 'Attack', 'Bridge to Point', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (99, 25, 1, 'Attack', 'White Room to Point', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (100, 25, 2, 'Defend', 'Bridge to Point', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (101, 25, 2, 'Defend', 'White Room to Point', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (102, 26, 1, 'Attack', 'Main to Point', 16.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (103, 26, 1, 'Attack', 'Servers to Point', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (104, 26, 2, 'Defend', 'Main to Point', 16.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (105, 26, 2, 'Defend', 'Servers to Point', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (106, 27, 1, 'Attack', 'Main to Point', 16.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (107, 27, 1, 'Attack', 'Main to Point', 16);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (108, 27, 1, 'Attack', 'Underneath to Point', 22.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (109, 27, 2, 'Defend', 'Main to Point', 16.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (110, 27, 2, 'Defend', 'Main to Point', 16);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (111, 27, 2, 'Defend', 'Underneath to Point', 22.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (112, 28, 1, 'Attack', 'Main to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (113, 28, 1, 'Attack', 'Traffic Side to Point', 23.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (114, 28, 1, 'Attack', 'Under Bridge to Point', 22.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (115, 28, 2, 'Defend', 'Main to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (116, 28, 2, 'Defend', 'Traffic Side to Point', 23.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (117, 28, 2, 'Defend', 'Under Bridge to Point', 22.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (118, 29, 1, 'Attack', 'Main to Point', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (119, 29, 1, 'Attack', 'Lounge to Point', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (120, 29, 1, 'Attack', 'Cliff Tunnel to Point', 18.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (121, 29, 2, 'Defend', 'Main to Point', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (122, 29, 2, 'Defend', 'Lounge to Point', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (123, 29, 2, 'Defend', 'Cliff Tunnel to Point', 18.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (124, 30, 1, 'Attack', 'Stairs to Forward Choke', 15);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (125, 30, 1, 'Attack', 'Tunnel to High Ground to Forward Choke', 30.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (126, 30, 2, 'Defend', 'Main to Forward Choke', 24.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (127, 30, 2, 'Defend', 'Alley to Forward Choke', 24.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (128, 31, 1, 'Attack', 'Stairs to Checkpoint', 21);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (129, 31, 2, 'Defend', 'Main to Checkpoint', 16.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (130, 31, 2, 'Defend', 'Alley to Checkpoint', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (131, 32, 1, 'Attack', 'Alley to Forward Corner', 17.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (132, 32, 1, 'Attack', 'Alley to Forward Corner', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (133, 32, 1, 'Attack', 'Main to Forward Corner', 14.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (134, 32, 2, 'Defend', 'Vault to Forward Corner', 23.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (135, 32, 2, 'Defend', 'High Ground to Forward Corner', 25.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (136, 32, 2, 'Defend', 'Coast Side to Forward Corner', 28.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (137, 32, 2, 'Defend', 'Coast Through Church to Forward Corner', 28.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (138, 32, 2, 'Defend', 'Main to Forward Corner', 23.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (139, 33, 1, 'Attack', 'Alley to Checkpoint', 26.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (140, 33, 1, 'Attack', 'Alley to Checkpoint', 26.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (141, 33, 1, 'Attack', 'Main to Checkpoint', 23.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (142, 33, 1, 'Attack', 'Coast Side to Checkpoint', 24.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (143, 33, 2, 'Defend', 'Left Spawn to Checkpoint', 13.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (144, 33, 2, 'Defend', 'Right Spawn to Checkpoint', 13.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (145, 33, 2, 'Defend', 'Vault to Checkpoint', 17);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (146, 34, 1, 'Attack', 'Main to Forward Corner', 20.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (147, 34, 1, 'Attack', 'Stairs to Forward Corner', 21.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (148, 34, 2, 'Defend', 'Main to Forward Corner', 15.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (149, 35, 1, 'Attack', 'Main to Checkpoint', 24.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (150, 35, 1, 'Attack', 'Stairs to Checkpoint', 25.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (151, 35, 1, 'Attack', 'Tunnel to Checkpoint', 25.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (152, 35, 2, 'Defend', 'Left Spawn to Checkpoint', 11);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (153, 35, 2, 'Defend', 'Far Right to Checkpoint', 12.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (154, 35, 2, 'Defend', 'Right Spawn to Checkpoint', 12.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (155, 36, 1, 'Attack', 'Main to Forward Choke', 16.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (156, 36, 1, 'Attack', 'Upper Spawn to Forward Choke', 17.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (157, 36, 2, 'Defend', 'Main to Forward Choke', 20);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (158, 36, 2, 'Defend', 'Connector to Forward Choke', 20);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (159, 37, 1, 'Attack', 'High Ground Connector to Checkpoint', 21.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (160, 37, 1, 'Attack', 'Main to Checkpoint', 21.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (161, 37, 1, 'Attack', 'Main Connector to Checkpoint', 22.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (162, 37, 2, 'Defend', 'Right Door to Checkpoint', 13.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (163, 37, 2, 'Defend', 'Left Door to Checkpoint', 15.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (164, 38, 1, 'Attack', 'Right Door to Forward Corner', 18.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (165, 38, 1, 'Attack', 'Right Spawn Left Door to Forward Corner', 20.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (166, 38, 1, 'Attack', 'High Ground to Forward Corner', 17.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (167, 38, 1, 'Attack', 'Right Door Over Boxes to Forward Corner', 17.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (168, 38, 1, 'Attack', 'Left Spawn Left Door to Forward Corner', 18.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (169, 38, 2, 'Defend', 'Boxes to Forward Corner', 16.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (170, 38, 2, 'Defend', 'Shuttle to Forward Corner', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (171, 39, 1, 'Attack', 'Right Door Over Boxes to Checkpoint', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (172, 39, 1, 'Attack', 'High Ground to Checkpoint', 22.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (173, 39, 1, 'Attack', 'Left Door to Checkpoint ', 23.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (174, 39, 2, 'Defend', 'Right Spawn Lower to Checkpoint', 12.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (175, 39, 2, 'Defend', 'Boxes to Checkpoint', 12.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (176, 39, 2, 'Defend', 'Right Spawn High Ground to Checkpoint', 12.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (177, 40, 1, 'Attack', 'Main to Forward Corner', 13.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (178, 40, 2, 'Defend', 'Left Spawn to Forward Corner', 17.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (179, 40, 2, 'Defend', 'Right Spawn to Forward Corner', 14.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (180, 41, 1, 'Attack', 'Main to Checkpoint', 20.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (181, 41, 2, 'Defend', 'Left Spawn to Checkpoint', 12.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (182, 41, 2, 'Defend', 'Right Spawn to Checkpoint', 8.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (183, 42, 1, 'Attack', 'Main to Forward Corner', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (184, 42, 1, 'Attack', 'Lower Mines to Forward Corner', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (185, 42, 1, 'Attack', 'High Ground to Forward Corner', 16.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (186, 42, 2, 'Defend', 'High Ground to Forward Corner', 23);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (187, 42, 2, 'Defend', 'Lower Left Tunnel to Forward Corner', 24.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (188, 43, 1, 'Attack', 'High Ground Through Gas to Checkpoint', 21.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (189, 43, 1, 'Attack', 'Lower Mines to Checkpoint ', 21);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (190, 43, 1, 'Attack', 'High Ground Behind Gas to Checkpoint', 23.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (191, 43, 2, 'Defend', 'High Ground to Checkpoint', 17.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (192, 43, 2, 'Defend', 'Lower Left Tunnel to Checkpoint', 18.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (193, 43, 2, 'Defend', 'Lower Right Tunnel to Checkpoint', 18);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (194, 44, 1, 'Attack', 'Canyon to Forward Corner', 16.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (195, 44, 1, 'Attack', 'Lower Right Tunnel to Forward Corner', 18.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (196, 44, 2, 'Defend', 'High Ground to Forward Corner', 22.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (197, 44, 2, 'Defend', 'Lower Left Tunnel through Saloon to Forward Corner', 29.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (198, 45, 1, 'Attack', 'Lower Right Tunnel to Stairs to Checkpoint', 21.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (199, 45, 1, 'Attack', 'Lower Right Tunnel to Mega Room to Checkpoint', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (200, 45, 1, 'Attack', 'Canyon to Stairs to Checkpoint', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (201, 45, 1, 'Attack', 'Canyon through Saloon to Checkpoint', 21.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (202, 45, 1, 'Attack', 'Lower Right Tunnel through Saloon to Checkpoint', 21.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (203, 45, 2, 'Defend', 'High Ground to Checkpoint', 16.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (204, 45, 2, 'Defend', 'Lower Left Tunnel to Checkpoint ', 22.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (205, 46, 1, 'Attack', 'Lower Left Tunnel to Forward Corner', 11.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (206, 46, 2, 'Defend', 'High Ground to Forward Corner', 17.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (207, 46, 2, 'Defend', 'Left Spawn Main to Forward Corner', 18.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (208, 46, 2, 'Defend', 'Right Spawn Main to Forward Corner', 18.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (209, 47, 1, 'Attack', 'Lower Left Tunnel to Checkpoint', 19.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (210, 47, 1, 'Attack', 'Stairs to Upper Right Tunnel to Checkpoint', 31.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (211, 47, 2, 'Defend', 'Left Spawn to Checkpoint', 9.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (212, 47, 2, 'Defend', 'Right Spawn to Checkpoint', 9.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (213, 48, 1, 'Attack', 'Main to Point', 21.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (214, 48, 1, 'Attack', 'Lower Tunnel to Point', 21.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (215, 48, 1, 'Attack', 'Upper Tunnel to Point', 23.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (216, 48, 1, 'Attack', 'Left Cliff to Point', 25.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (217, 48, 2, 'Defend', 'Main to Point', 18.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (218, 48, 2, 'Defend', 'Shop Tunnel to Point ', 22.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (219, 49, 1, 'Attack', 'Main to Forward Corner', 13);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (220, 49, 2, 'Defend', 'Main to Forward Corner', 30.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (221, 49, 2, 'Defend', 'Stairs to High Ground to Forward Corner', 33.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (222, 50, 1, 'Attack', 'Main Through Clothes Shop to Checkpoint', 20.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (223, 50, 1, 'Attack', 'Main to Checkpoint', 21);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (224, 50, 2, 'Defend', 'Main to Checkpoint', 21.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (225, 50, 2, 'Defend', 'Stairs to High Ground to Checkpoint', 23.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (226, 51, 1, 'Attack', 'Main to Forward Corner', 16.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (227, 51, 1, 'Attack', 'Stairs to High Ground to Forward Corner', 20.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (228, 51, 1, 'Attack', 'Stairs through Mega Lounge to Forward Corner', 25.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (229, 51, 2, 'Defend', 'Main to Forward Corner', 18.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (230, 51, 2, 'Defend', 'Small Health Room to Forward Corner', 17.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (231, 51, 2, 'Defend', 'Right Cliff to Forward Corner', 17.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (232, 52, 1, 'Attack', 'Main to Checkpoint', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (233, 52, 1, 'Attack', 'Small Health Room to Checkpoint', 23);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (234, 52, 1, 'Attack', 'Left Cliff to Checkpoint', 24.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (235, 52, 1, 'Attack', 'Stairs to High Ground to Checkpoint', 24.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (236, 52, 2, 'Defend', 'Left Spawn to Checkpoint', 10.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (237, 52, 2, 'Defend', 'Right Spawn to Checkpoint', 10.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (238, 53, 1, 'Attack', 'Main to Forward Choke', 14.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (239, 53, 1, 'Attack', 'Left through Bar Stairs to Forward Choke', 20);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (240, 53, 2, 'Defend', 'Cafe to Forward Choke', 22.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (241, 53, 2, 'Defend', 'Dark Room to Point', 20.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (242, 54, 1, 'Attack', 'Main to Point', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (243, 54, 1, 'Attack', 'Security Room to Point', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (244, 54, 1, 'Attack', 'Alley to Point', 22);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (245, 54, 2, 'Defend', 'Cafe to Point', 17.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (246, 54, 2, 'Defend', 'Dark Room to Point', 18.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (247, 55, 1, 'Attack', 'Main to Forward Choke', 13.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (248, 55, 2, 'Defend', 'Left Alley to Forward Choke', 26.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (249, 55, 2, 'Defend', 'Main to Forward Choke', 26);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (250, 56, 1, 'Attack', 'Main to Mid Streets', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (251, 56, 2, 'Defend', 'Left Door Main to Mid Streets', 20.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (252, 56, 2, 'Defend', 'Right Door Alley to Mid Streets', 20.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (253, 56, 2, 'Defend', 'Left Door through Saloon to Mid Streets', 20.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (254, 57, 1, 'Attack', 'Left Alley to Checkpoint', 22.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (255, 57, 1, 'Attack', 'Right Alley to Checkpoint', 27);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (256, 57, 1, 'Attack', 'Main to Checkpoint', 23.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (257, 57, 1, 'Attack', 'Main through Saloon to Checkpoint', 22.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (258, 57, 2, 'Defend', 'Left Door to Checkpoint', 13.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (259, 57, 2, 'Defend', 'Right Door to Checkpoint', 16.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (260, 58, 1, 'Attack', 'Main to Forward Corner', 10.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (261, 58, 2, 'Defend', 'Stairs to High Ground to Forward Corner', 17.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (262, 58, 2, 'Defend', 'Main to Forward Corner', 19.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (263, 59, 1, 'Attack', 'Main to Checkpoint', 18.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (264, 59, 2, 'Defend', 'Left Spawn to Checkpoint', 9.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (265, 59, 2, 'Defend', 'Right Spawn to Checkpoint', 10.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (266, 60, 1, 'Attack', 'Main to Forward Choke', 11.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (267, 60, 2, 'Defend', 'Main through Hotel to Forward Choke', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (268, 60, 2, 'Defend', 'Main by Point to Forward Choke', 22);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (269, 60, 2, 'Defend', 'Left through Apartments to Forward Choke', 26.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (270, 61, 1, 'Attack', 'Main to Point', 14.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (271, 61, 1, 'Attack', 'Main Through Hotel to Point', 15.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (272, 61, 1, 'Attack', 'Cinema past Choke to Point', 22.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (273, 61, 2, 'Defend', 'Left through Main to Point', 17.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (274, 61, 2, 'Defend', 'Left through Apartments to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (275, 62, 1, 'Attack', 'Main to Forward Choke', 12.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (276, 62, 2, 'Defend', 'Main to Forward Choke', 32.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (277, 62, 2, 'Defend', 'Bar Alley High Ground to Forward Choke', 34.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (278, 63, 1, 'Attack', 'Main to Forward Corner', 16.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (279, 63, 1, 'Attack', 'Right Spawn Stairs to High Ground to Forward Corner', 19);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (280, 63, 1, 'Attack', 'Right Spawn through Apartments to Forward Corner', 17.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (281, 63, 2, 'Defend', 'Main to Forward Corner', 28.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (282, 63, 2, 'Defend', 'Bar Alley High Ground to Forward Corner', 30.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (283, 64, 1, 'Attack', 'Main to Checkpoint', 24.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (284, 64, 1, 'Attack', 'Right Spawn Stairs to High Ground through Distillery to Checkpoint', 29.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (285, 64, 1, 'Attack', 'Main through Left Alley to Checkpoint', 27);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (286, 64, 2, 'Defend', 'Main to Checkpoint', 19.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (287, 65, 1, 'Attack', 'Left Small Health to Forward Corner', 14.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (288, 65, 1, 'Attack', 'Main to Forward Corner', 14.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (289, 65, 1, 'Attack', 'Right Spawn Stairs to High Ground to Forward Corner', 15.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (290, 65, 2, 'Defend', 'Left Main to Forward Corner', 16.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (291, 65, 2, 'Defend', 'Right Main to Forward Corner', 17);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (292, 66, 1, 'Attack', 'Main to Checkpoint', 21.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (293, 66, 2, 'Defend', 'Left Spawn to Checkpoint', 9.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (294, 66, 2, 'Defend', 'Right Spawn to Checkpoint', 9.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (295, 67, 1, 'Attack', 'Main to Forward Choke', 13.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (296, 67, 1, 'Attack', 'Upper Right Spawn to Forward Choke', 14.3);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (297, 67, 1, 'Attack', 'Main through Mega Room to Forward Choke', 14.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (298, 67, 2, 'Defend', 'Main Left to Forward Choke', 21.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (299, 67, 2, 'Defend', 'Main Right to Forward Choke', 24.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (300, 67, 2, 'Defend', 'Left Spawn through Cafe High Ground to Forward Choke', 26.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (301, 68, 1, 'Attack', 'Main Left to Point', 17.7);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (302, 68, 1, 'Attack', 'Main Right to Point', 18.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (303, 68, 1, 'Attack', 'Upper Right Spawn to Main Left to Point', 18.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (304, 68, 1, 'Attack', 'Upper Right Spawn to Main Right to Point', 19.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (305, 68, 2, 'Defend', 'Main to Point', 17.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (306, 68, 2, 'Defend', 'Right Spawn through Cafe High Ground to Point', 22.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (307, 68, 2, 'Defend', 'Main through Cafe High Ground to Point', 20.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (308, 69, 1, 'Attack', 'Main Tunnel to Forward Corner ', 13.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (309, 69, 1, 'Attack', 'Cafe Stairs to Tunnel to Forward Corner', 17.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (310, 69, 2, 'Defend', 'Over Castle to Forward Corner', 18.2);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (311, 69, 2, 'Defend', 'Through Castle to Forward Corner', 18);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (312, 70, 1, 'Attack', 'Main Tunnel to Mid Choke', 16.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (313, 70, 1, 'Attack', 'Cafe Stairs to Tunnel to Mid Choke', 20.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (314, 70, 2, 'Defend', 'Over Castle to Mid Choke', 18.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (315, 70, 2, 'Defend', 'Through Castle to Mid Choke', 18.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (316, 70, 2, 'Defend', 'Main to Mid Choke', 20.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (317, 71, 1, 'Attack', 'Main Tunnel through Castle to Checkpoint', 21.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (318, 71, 1, 'Attack', 'Cafe Stairs through Tunnel to Main to Checkpoint', 28.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (319, 71, 2, 'Defend', 'Left Door to Checkpoint', 13.1);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (320, 71, 2, 'Defend', 'Right Door to Checkpoint', 12.8);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (321, 72, 1, 'Attack', 'Main to Forward Choke', 14.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (322, 72, 2, 'Defend', 'Left Main to Forward Choke', 16.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (323, 72, 2, 'Defend', 'Right Main to Forward Choke', 17.9);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (324, 73, 1, 'Attack', 'Main to Forward Corner', 18.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (325, 73, 2, 'Defend', 'Left Main to Forward Corner', 14.6);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (326, 74, 1, 'Attack', 'Main to Checkpoint', 22.4);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (327, 74, 2, 'Defend', 'Left Spawn to Checkpoint', 8.5);
INSERT INTO MapSpawnStatistics (StatisticId, LocationId, SpawnSideId, SpawnSideDescription, RunDescription, RunDuration) VALUES (328, 74, 2, 'Defend', 'Right Spawn to Checkpoint', 8.7);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
